# Generated by Django 4.1.3 on 2024-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='empty', max_length=100)),
                ('field_value', models.CharField(default='value', max_length=255)),
                ('selection_value', models.CharField(default='value', max_length=100)),
                ('required', models.BooleanField(default=None, null=True)),
                ('readable', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(default='empty', max_length=100)),
                ('forms_name', models.CharField(default='value', max_length=255)),
                ('Rediretpath_name', models.CharField(default='value', max_length=100)),
            ],
        ),
    ]
