# Generated by Django 4.2.5 on 2024-03-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraggableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_value', models.CharField(max_length=255)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebTabs.fielddata')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebTabs.formdata')),
            ],
        ),
    ]
