# Generated by Django 4.2.5 on 2024-03-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0003_draggabledata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraggableData',
        ),
    ]
